services:
  - type: web
    name: madridtours
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://YOUR-APP-NAME.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: ADMIN_NAME
        value: Amr
      - key: ADMIN_EMAIL
        value: amrkfawzy@gmail.com
      - key: ADMIN_PASSWORD
        value: 787898787899
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
